version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: qwe123
      MYSQL_DATABASE: anyprocess
    ports:
      - "3306:3306"
    volumes:
      - ./database/script_anyprocess.sql:/docker-entrypoint-initdb.d/1.sql
  
  anyprocess:
    build: .
    container_name: anyprocess
    environment:
      - CATALINA_OPTS=-Duser.timezone=America/Belem -Duser.country=BR -Duser.language=pt
    ports:
      - 8080:8080
    depends_on:
      - mysql



